// app/(user)/layout.jsx
import { Geist, Geist_Mono } from 'next/font/google';
import Footer from '../components/user/Footer/footer';
import Navbar from '../components/user/Navbar/navbar';
import TopHeader from '../components/user/TopHeader/topHeader';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
};

export default function UserLayout({ children }) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <TopHeader />
      <Navbar />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
